### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by remkoboschker** [jonschlinkert/gulp-frep#2]
Hi, 

Your missing the dependencies event-stream and lodash.

**Comment by jonschlinkert** [comment]
Lodash isn't used anywhere in the plugin or the tests, and event-stream was in devDependencies - so it still should have worked except for edge cases. I updated it to be in dependencies though. 

were you getting an error?

**Comment by remkoboschker** [comment]
Hi, 

Yes I got an error that the modules could not be found. I later realised I should have used npm install --dev. Thanks.

**Comment by jonschlinkert** [comment]
No prob, thanks!
